CREATE DATABASE RedeSocial2

USE RedeSocial2

CREATE TABLE TB_USUARIOS(
ID_Usuarios INT NOT NULL PRIMARY KEY,
Nome varchar(250) NOT NULL,
Usuario varchar(250) NOT NULL,
Senha varchar(250) NOT NULL,
CPF int NOT NULL,
);

CREATE TABLE tb_postagens(
	Id_postagem INT NOT NULL PRIMARY KEY,
	Titulo VARCHAR (50) NOT NULL,
	Descricao VARCHAR (1000) NOT NULL,
	url_imagem VARCHAR (100) NOT NULL,
	FK_Criador INT,
	FOREIGN KEY (FK_Criador) REFERENCES tb_usuarios (Id_usuarios),
	FK_Grupo INT,
	FOREIGN KEY (FK_Grupo) REFERENCES TB_GRUPOS (Id_Grupos),
	);

CREATE TABLE TB_GRUPOS(
ID_GRUPOS INT NOT NULL PRIMARY KEY,
GRUPO VARCHAR (250) NOT NULL,
DESCRICAO VARCHAR (250) NOT NULL,
URL_IMAGEM VARCHAR (250) NOT NULL,
FK_Criador INT,
FOREIGN KEY (FK_Criador) REFERENCES TB_USUARIOS (Id_Usuarios)
);

CREATE TABLE TB_INSCRITOS(
FK_CRIADOR INT,
FK_CRIADOR2 INT,
DATA_HORAS DATE NOT NULL,
FOREIGN KEY (FK_CRIADOR) REFERENCES TB_USUARIOS (Id_Usuarios),
FOREIGN KEY (FK_CRIADOR2) REFERENCES TB_GRUPOS (ID_GRUPOS),
);

INSERT INTO TB_USUARIOS
VALUES 
(01, 'Fabio', 'fabinrag', 'raglover', 47679725),
(02, 'Vinicius', 'vinaodamassa', 'futamericano', 47679726),
(03, 'Amanda', 'MandinhaHtinha', 'faztudo', 47679727),
(04, 'thaina', 'thaibarbs', '123456', 47679728);

SELECT * FROM TB_USUARIOS
WHERE  NOME LIKE 'A%';